#!/bin/sh
: <<COMMENTBLOCK

check_process=( "polybar" "bspwm" )
check_not_running=("gnome-shell" "xfce4-session" "fvwm")
should_be_two=0


for p in "${check_process[@]}"; do
	if pgrep "$p" > /dev/null; then
		(( should_be_two++ ))
	fi
done


if (( $should_be_two == 2 )); then
	pkill polybar
	echo "polyReload: polybar has been restarted with the new color scheme"
	polybar -c ~/.config/polybar/config -q example &
else
	if pgrep "gnome-shell" > /dev/null; then
		echo "polyReload: since gnome is running, polybar will not be loaded"
	else
		if pgrep "fvwm" > dev/null; then
			echo "polyReload: since fvwm is running, polybar will not be loaded"
		else
			echo "polyReload: polybar has been started with the new color scheme"
			polybar -c ~/.config/polybar/config -q example &
		fi
	fi

fi

COMMENTBLOCK

wal-discord -b wal -t
echo "wal-discord: Set Discord colors"

echo "Oomox: refreshing theme colors, this may take up to a minute..."
nohup oomox-cli -o xresources /opt/oomox/scripted_colors/xresources/xresources > /dev/null 2>&1
nohup oomox-cli -o xresources2 /opt/oomox/scripted_colors/xresources/xresources2 > /dev/null 2>&1
nohup oomox-cli -o xresources3 /opt/oomox/scripted_colors/xresources/xresources3 > /dev/null 2>&1
echo "Oomox: oomox has finished refreshing theme colors"

echo "Oomox: reloading Spotify with new colors..."
nohup /home/macrossneurology/DotsMine/scripts/oomox-spotify-colors.sh > /dev/null 2>&1
echo "Oomox: oomox has finished reloading Spotify with new colors"
