#!/bin/sh

#killall -9 gifview
#feh --bg-fill "$HOME/Pictures/butterfly.jpg"
#feh --recursive --randomize --bg-fill ~/Pictures/Wallpapers/print/
#feh --recursive --randomize --bg-fill ~/Pictures/Wallpapers/Colors/
#feh --recursive --randomize --bg-fill ~/Pictures/Wallpapers/Touhou/
#feh --recursive --randomize --bg-fill ~/Pictures/Wallpapers/Chiptunes/
#feh --recursive --randomize --bg-fill ~/Pictures/Wallpapers/Floam/
#feh --recursive --randomize --bg-fill ~/Pictures/Wallpapers/nice-real/
#feh --recursive --randomize --bg-fill ~/Pictures/Wallpapers/glitch/
#feh --recursive --randomize --bg-fill ~/Pictures/Wallpapers/Impressionism/
#feh --recursive --randomize --bg-fill ~/Pictures/Wallpaers/

#hm="/home/macrosscerebral"

choice="$1"

if [ "$choice" = "rand" ]; then
	choice=$(((RANDOM % 18 ) + 1 ))
fi


case "$choice" in

1) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/Chiptune/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

2) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/glitch/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

3) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/Colors/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

4) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/Touhou/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

5) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/Floam/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

6) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/Impressionism/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

7) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/print/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

8) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/Pastel/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

9) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/dream/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

10) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/Mandelbrot/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

11) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/Miscolour/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

12) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/abstractions/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

13) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/Winter/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

14) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/Minerals/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

15) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/Hallow/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

16) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/Forestry/' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

17) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/Deprecation' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

18) wal -g -i '/home/macrosscerebral/Pictures/Wallpapers/WalCompatible/Space' -t
echo "choice is $choice" >> ~/set_bg.log
/home/macrosscerebral/DotsMine/scripts/polyReload
wal_steam
;;

*) if [ -z "$choice" ]; then
	echo "No number given"
	exit 1
else
	echo "Not a set number"
	exit 1
fi

;;

esac

#bash ~/wal-set
